{{- if .Values.enabled }}
{{- if .Values.operator }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}-operator
  namespace: {{ .Values.namespace }}
spec:
  channel: {{ .Values.operator.channel }}
  name: {{ .Values.operator.name }}
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- end }}
